[build]
builder = "nixpacks"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "always"
startCommand = "gunicorn app:app --bind 0.0.0.0:$PORT --workers 2 --timeout 120"

[environments.production.variables]
FLASK_ENV = "production"
PYTHONPATH = "."
