[build]
builder = "nixpacks"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "always"

[environments.production.variables]
FLASK_ENV = "production"
PYTHONPATH = "."
